import { ActivatedRoute } from '@angular/router';
import { Component, OnInit } from '@angular/core';
@Component({
  selector: 'app-itemRecommedation',
  host: {'class': 'card mb-5 mb-xl-8'},
  templateUrl: './itemRecommedation.component.html',
})
export class ItemRecommedationComponent implements OnInit {
  RecommendationItems: { ItemName: string; RecItems: string[]; }[];
  constructor(private route: ActivatedRoute) {}
  // RecommendationItems=[{itemName:"",}]
  ngOnInit(): void {
    this.route.data.subscribe(data => {
      console.log(data);
  })

    this.RecommendationItems =
    // [
    //   {"ItemName":"Item1" , "RecItems":["Item11","Item11","Item11","Item11","Item11"]},
    //   {"ItemName":"Item2" , "RecItems":["Item21","Item21","Item21","Item21","Item21"]},
    //   {"ItemName":"Item3" , "RecItems":["Item31","Item11","Item11","Item11","Item11"]},
    //   {"ItemName":"Item4" , "RecItems":["Item11","Item11","Item11","Item11","Item11"]},
    //   {"ItemName":"Item3" , "RecItems":["Item31","Item11","Item11","Item11","Item11"]},
    //   {"ItemName":"Item4" , "RecItems":["Item11","Item11","Item11","Item11","Item11"]},
    //   {"ItemName":"Item3" , "RecItems":["Item31","Item11","Item11","Item11","Item11"]},
    //   {"ItemName":"Item4" , "RecItems":["Item11","Item11","Item11","Item11","Item11"]},

    // ]
    [{'ItemName': 'Tnuva Amek Cheese                       ',
  'RecItems': ['Siniora Turkey Breast Pabrika           ',
   'Siniora Bbq                             ',
   'Mays Hodlavan Turkey Breast             ',
   'Oaf Tof Breast And Basterma             ',
   'Salami Oaf Tof                          ',
   'Sin Roast Beef Plain                    ']},
 {'ItemName': 'Produce 9 Nis                           ',
  'RecItems': ['Produce 10 Nis                          ',
   'Produce 12 Nis                          ',
   'Produce 8 Nis                           ',
   'Produce 5 Nis                           ',
   'Produce 8 Nis                           ',
   'Produce 7 Nis                           ']},
 {'ItemName': 'Baby Wipes Red                          ',
  'RecItems': ['Baby Wipes Purple                       ',
   'Baby Wipes Tango                        ',
   'Baby Wipes Tango                        ']},
 {'ItemName': 'Twix 50G                                ',
  'RecItems': ['Snickers 50G                            ',
   'Bounty 57G                              ',
   'Bounty 57G                              ',
   'Mars 51G                                ',
   'Mars 51G                                ',
   'Mars 51G                                ']},
 {'ItemName': 'Snickers 50G                            ',
  'RecItems': ['Twix 50G                                ',
   'Bounty 57G                              ',
   'Mars 51G                                ',
   'Mars 51G                                ',
   'Mars 51G                                ',
   'Bounty 57G                              ']},
 {'ItemName': 'Cappy Mango 1.5L                        ',
  'RecItems': ['Cappy Strawberry & Banana Drink 1.5L    ',
   'Cappy Orange 1.5L                       ',
   'Cappy Pear Kiwi & Cactus1.5L            ',
   'Cappy Grape 1.5L                        ']},
 {'ItemName': 'Cappy Strawberry & Banana Drink 1.5L    ',
  'RecItems': ['Cappy Grape 1.5L                        ',
   'Cappy Orange 1.5L                       ',
   'Cappy Mango 1.5L                        ',
   'Cappy Red Cherry  1.5L                  ',
   'Cappy Pear Kiwi & Cactus1.5L            ']},
 {'ItemName': 'Cappy Lemon Mint Drink 1.5 L            ',
  'RecItems': ['Cappy Orange 1.5L                       ',
   'Cappy Grape 1.5L                        ']},
 {'ItemName': 'Fairy Lemon 16*650Ml                    ',
  'RecItems': ['Fairy Lemon 9*1240 Ml                   ',
   'Fairy Original 9*1240 M                 ']},
 {'ItemName': 'Fairy Lemon 9*1240 Ml                   ',
  'RecItems': ['Fairy Lemon 16*650Ml                    ',
   'Fairy Orginal 16*650Ml                  ']},
 {'ItemName': 'Seven Up 1L                             ',
  'RecItems': ['Pepsi 1L                                ',
   'Mirinda 1L                              ',
   'Pepsi 1L                                ']},
 {'ItemName': 'Produce 3.33 Nis                        ',
  'RecItems': ['Produce 7 Nis                           ',
   'Produce 7 Nis                           ',
   'Produce 7 Nis                           ',
   'Produce 8 Nis                           ',
   'Produce 5 Nis                           ',
   'Produce 7 Nis                           ']},
 {'ItemName': 'Produce 5 Nis                           ',
  'RecItems': ['Produce 8 Nis                           ',
   'Produce 9 Nis                           ',
   'Produce 7 Nis                           ',
   'Produce 7 Nis                           ',
   'Produce 3.33 Nis                        ',
   'Produce 3.33 Nis                        ']},
 {'ItemName': 'Produce 10 Nis                          ',
  'RecItems': ['Produce 9 Nis                           ',
   'Produce 3.33 Nis                        ',
   'Produce 3.33 Nis                        ',
   'Produce 7 Nis                           ',
   'Produce 3.33 Nis                        ',
   'Produce 8 Nis                           ']},
 {'ItemName': 'Produce 7 Nis                           ',
  'RecItems': ['Produce 5 Nis                           ',
   'Produce 8 Nis                           ',
   'Produce 3.33 Nis                        ',
   'Produce 3.33 Nis                        ',
   'Produce 3.33 Nis                        ',
   'Produce 3.33 Nis                        ']},
 {'ItemName': 'Fanta Orange 1.125L                     ',
  'RecItems': ['Coca Cola 1.125L                        ',
   'Sprite 1.125L                           ',
   'Coca Cola 1.125L                        ']},
 {'ItemName': 'Pringles Original 18*165Gr              ',
  'RecItems': ['Pringles Sour Cream 18*165Gr            ',
   'Pringles Hot & Spicy 18*165Gr           ']},
 {'ItemName': 'Produce 15 Nis                          ',
  'RecItems': ['Produce 10 Nis                          ',
   'Produce 12 Nis                          ',
   'Produce 5 Nis                           ',
   'Produce 7 Nis                           ',
   'Produce 6 Nis                           ',
   'Produce 8 Nis                           ']},
 {'ItemName': 'Produce 4 Nis                           ',
  'RecItems': ['Produce 3.33 Nis                        ',
   'Produce 6 Nis                           ',
   'Produce 7 Nis                           ',
   'Produce 7 Nis                           ',
   'Produce 7 Nis                           ',
   'Produce 7 Nis                           ']},
 {'ItemName': 'Produce 12 Nis                          ',
  'RecItems': ['Produce 9 Nis                           ',
   'Produce 15 Nis                          ',
   'Produce 8 Nis                           ',
   'Produce 7 Nis                           ',
   'Produce 10 Nis                          ',
   'Produce 8 Nis                           ']},
 {'ItemName': 'Bavaria Strawberry Can 330Ml            ',
  'RecItems': ['Bavaria Apple Can 330Ml                 ',
   'Bavaria Peach Can 330Ml                 ',
   'Bavaria Pomegranate Can 330L            ']},
 {'ItemName': 'Doritos W Pepper 45G                    ',
  'RecItems': ['Doritos W/Grill 45G                     ',
   'Tabochips Lays 40G                      ']},
 {'ItemName': 'Baby Wipes Purple                       ',
  'RecItems': ['Baby Wipes Red                          ',
   'Baby Wipes Tango                        ',
   'Baby Wipes Tango                        ']},
 {'ItemName': 'Sin. Al Quds Mort P.O.P                 ',
  'RecItems': ['Homos Extra 250G                        ',
   'Mixed Salad 125G                        ']},
 {'ItemName': 'Mixed Salad 125G                        ',
  'RecItems': ['Sin. Al Quds Mort P.O.P                 ',
   'Al Junaidi Corn Salad 125G              ']},
 {'ItemName': 'Coca Cola 1.125L                        ',
  'RecItems': ['Fanta Orange 1.125L                     ',
   'Fanta Orange 1.125L                     ',
   'Sprite 1.125L                           ']},
 {'ItemName': 'Produce Unit 12  Nis                    ',
  'RecItems': ['Produce 3.33 Nis                        ',
   'Produce Unit 5 Nis                      ',
   'Produce 6 Nis                           ',
   'Produce 4 Nis                           ',
   'Produce 7 Nis                           ',
   'Produce 7 Nis                           ']},
 {'ItemName': 'Sprite 1.125L                           ',
  'RecItems': ['Fanta Orange 1.125L                     ',
   'Coca Cola 1.125L                        ',
   'Coca Cola 1.125L                        ']},
 {'ItemName': 'Cappy Grape 1.5L                        ',
  'RecItems': ['Cappy Strawberry & Banana Drink 1.5L    ',
   'Cappy Mango 1.5L                        ',
   'Cappy Lemon Mint Drink 1.5 L            ',
   'Cappy Red Cherry  1.5L                  ',
   'Cappy Orange 1.5L                       ',
   'Cappy Grapefruit 1.5 L                  ']},
 {'ItemName': 'Cappy Red Cherry  1.5L                  ',
  'RecItems': ['Cappy Grape 1.5L                        ',
   'Cappy Orange 1.5L                       ',
   'Cappy Strawberry & Banana Drink 1.5L    ',
   'Cappy Pear Kiwi & Cactus1.5L            ']},
 {'ItemName': 'Produce Unit 5 Nis                      ',
  'RecItems': ['Produce Unit 12  Nis                    ',
   'Produce 3.33 Nis                        ',
   'Produce 4 Nis                           ',
   'Produce 3.33 Nis                        ',
   'Produce 3.33 Nis                        ',
   'Produce 8 Nis                           ']},
 {'ItemName': 'Produce Unit 10 Nis                     ',
  'RecItems': ['Produce 3.33 Nis                        ',
   'Produce Unit 5 Nis                      ',
   'Produce 4 Nis                           ',
   'Produce 3.33 Nis                        ',
   'Produce 3.33 Nis                        ',
   'Produce 5 Nis                           ']},
 {'ItemName': 'Produce 13 Nis                          ',
  'RecItems': ['Produce 15 Nis                          ',
   'Produce 10 Nis                          ',
   'Produce 12 Nis                          ',
   'Produce 7 Nis                           ',
   'Produce 7 Nis                           ',
   'Produce 8 Nis                           ']},
 {'ItemName': 'Produce 20 Nis                          ',
  'RecItems': ['Produce 15 Nis                          ',
   'Produce 12 Nis                          ',
   'Produce 7 Nis                           ',
   'Produce 8 Nis                           ']},
 {'ItemName': 'Osem Zaatar Snack Cracker 300G          ',
  'RecItems': ['Crackerbegala 400G 8 Shape              ',
   'Crackerbegala Salty  Figners 375G       ']},
 {'ItemName': 'Safi Sunflower Oil 5L                   ',
  'RecItems': ['Addyafe Basmati Rice 5K                 ',
   'Abu Eta Noodles 200G                    ']},
 {'ItemName': 'Salt Salit 1K 1*12                      ',
  'RecItems': ['Al Sanabel Wheat Flour 1K               ',
   'Alraya Sugar 1K                         ',
   'Haifa Flour 1K                          ',
   'Rice Shukha Sunwhite 5K                 ']},
 {'ItemName': 'Produce 8 Nis                           ',
  'RecItems': ['Produce 9 Nis                           ',
   'Produce 9 Nis                           ',
   'Produce 7 Nis                           ',
   'Produce 7 Nis                           ',
   'Produce 3.33 Nis                        ',
   'Produce 5 Nis                           ']},
 {'ItemName': 'Cappy Orange 1.5L                       ',
  'RecItems': ['Cappy Strawberry & Banana Drink 1.5L    ',
   'Cappy Mango 1.5L                        ',
   'Cappy Lemon Mint Drink 1.5 L            ',
   'Cappy Red Cherry  1.5L                  ',
   'Cappy Grape 1.5L                        ',
   'Cappy Grapefruit 1.5 L                  ']},
 {'ItemName': 'Roastery 40 Nis                         ',
  'RecItems': ['Roastery 56                             ',
   'Roastery 32 Nis                         ',
   'Roastery 36 Nis                         ',
   'Roastery 60 Nis                         ']},
 {'ItemName': 'Pringles Sour Cream 18*165Gr            ',
  'RecItems': ['Pringles Original 18*165Gr              ',
   'Pringles Hot & Spicy 18*165Gr           ']},
 {'ItemName': 'Alraya Sugar 1K                         ',
  'RecItems': ['Salt Salit 1K 1*12                      ',
   'Haifa Flour 1K                          ']},
 {'ItemName': 'Hand Soap Apple 500 Ml                  ',
  'RecItems': ['Hand Soap Rose 500 Ml                   ',
   'Hand Soap Peach 500 Ml                  ',
   'Hand Soap Oat 500 Ml                    ']},
 {'ItemName': 'Hand Soap Rose 500 Ml                   ',
  'RecItems': ['Hand Soap Apple 500 Ml                  ',
   'Hand Soap Aolevera 500 Ml               ',
   'Hand Soap Peach 500 Ml                  ',
   'Hand Soap Oat 500 Ml                    ']},
 {'ItemName': 'Pepsi 1L                                ',
  'RecItems': ['Seven Up 1L                             ',
   'Mirinda 1L                              ',
   'Seven Up 1L                             ']},
 {'ItemName': 'Bavaria Apple Can 330Ml                 ',
  'RecItems': ['Bavaria Strawberry Can 330Ml            ',
   'Bavaria Peach Can 330Ml                 ',
   'Bavaria Pomegranate Can 330L            ']},
 {'ItemName': 'Haifa Flour 1K                          ',
  'RecItems': ['Alraya Sugar 1K                         ',
   'Salt Salit 1K 1*12                      ']},
 {'ItemName': 'Produce 2.5 Nis                         ',
  'RecItems': ['Produce Unit 5 Nis                      ',
   'Produce 3.33 Nis                        ',
   'Produce 6 Nis                           ',
   'Produce 4 Nis                           ',
   'Produce Unit 12  Nis                    ',
   'Produce Unit 10 Nis                     ']},
 {'ItemName': 'Cappy Grapefruit 1.5 L                  ',
  'RecItems': ['Cappy Orange 1.5L                       ',
   'Cappy Grape 1.5L                        ']},
 {'ItemName': 'Cappy Pear Kiwi & Cactus1.5L            ',
  'RecItems': ['Cappy Mango 1.5L                        ',
   'Cappy Orange 1.5L                       ',
   'Cappy Grape 1.5L                        ',
   'Cappy Red Cherry  1.5L                  ',
   'Cappy Strawberry & Banana Drink 1.5L    ']},
 {'ItemName': 'Mars 51G                                ',
  'RecItems': ['Snickers 50G                            ',
   'Bounty 57G                              ',
   'Twix 50G                                ',
   'Bounty 57G                              ',
   'Bounty 57G                              ',
   'Twix 50G                                ']},
 {'ItemName': 'Produce 6 Nis                           ',
  'RecItems': ['Produce 5 Nis                           ',
   'Produce 8 Nis                           ',
   'Produce 7 Nis                           ',
   'Produce 3.33 Nis                        ',
   'Produce 3.33 Nis                        ',
   'Produce 3.33 Nis                        ']},
 {'ItemName': 'Seven Up 1.5L                           ',
  'RecItems': ['Pepsi 1.5L                              ',
   'Mirinda 1.5L                            ']},
 {'ItemName': 'Crackerbegala 400G 8 Shape              ',
  'RecItems': ['Osem Zaatar Snack Cracker 300G          ',
   'Crackerbegala Salty  Figners 375G       ']},
 {'ItemName': 'Baby Wipes Tango                        ',
  'RecItems': ['Baby Wipes Purple                       ',
   'Baby Wipes Red                          ',
   'Baby Wipes Purple                       ']},
 {'ItemName': 'Pringles Hot & Spicy 12*40Gr            ',
  'RecItems': ['Pringles Sour Cream  12*40Gr            ',
   'Pringles Original 12*40Gr               ',
   'Pringles Original 12*40Gr               ']},
 {'ItemName': 'Fairy Orginal 16*650Ml                  ',
  'RecItems': ['Fairy Lemon 9*1240 Ml                   ',
   'Fairy Original 9*1240 M                 ']},
 {'ItemName': 'Pringles Hot & Spicy 18*165Gr           ',
  'RecItems': ['Pringles Original 18*165Gr              ',
   'Pringles Sour Cream 18*165Gr            ']},
 {'ItemName': 'Bounty 57G                              ',
  'RecItems': ['Twix 50G                                ',
   'Twix 50G                                ',
   'Mars 51G                                ',
   'Mars 51G                                ',
   'Mars 51G                                ',
   'Snickers 50G                            ']},
 {'ItemName': 'Bavaria Peach Can 330Ml                 ',
  'RecItems': ['Bavaria Strawberry Can 330Ml            ',
   'Bavaria Apple Can 330Ml                 ',
   'Bavaria Pomegranate Can 330L            ']},
 {'ItemName': 'Pringles Original 12*40Gr               ',
  'RecItems': ['Pringles Hot & Spicy 12*40Gr            ',
   'Pringles Hot & Spicy 12*40Gr            ',
   'Pringles Sour Cream  12*40Gr            ']},
 {'ItemName': 'Pringles Sour Cream  12*40Gr            ',
  'RecItems': ['Pringles Hot & Spicy 12*40Gr            ',
   'Pringles Hot & Spicy 12*40Gr            ',
   'Pringles Original 12*40Gr               ']},
 {'ItemName': 'Hand Soap Peach 500 Ml                  ',
  'RecItems': ['Hand Soap Apple 500 Ml                  ',
   'Hand Soap Rose 500 Ml                   ',
   'Hand Soap Oat 500 Ml                    ']},
 {'ItemName': 'Bavaria Pomegranate Can 330L            ',
  'RecItems': ['Bavaria Strawberry Can 330Ml            ',
   'Bavaria Peach Can 330Ml                 ',
   'Bavaria Apple Can 330Ml                 ']},
 {'ItemName': 'Crackerbegala Salty  Figners 375G       ',
  'RecItems': ['Crackerbegala 400G 8 Shape              ',
   'Osem Zaatar Snack Cracker 300G          ']},
 {'ItemName': 'Fairy Original 9*1240 M                 ',
  'RecItems': ['Fairy Orginal 16*650Ml                  ',
   'Fairy Lemon 16*650Ml                    ']},
 {'ItemName': 'Mirinda 1L                              ',
  'RecItems': ['Seven Up 1L                             ',
   'Pepsi 1L                                ',
   'Pepsi 1L                                ']},
 {'ItemName': 'Hand Soap Oat 500 Ml                    ',
  'RecItems': ['Hand Soap Peach 500 Ml                  ',
   'Hand Soap Apple 500 Ml                  ',
   'Hand Soap Rose 500 Ml                   ']}]
  }
}
